#!/usr/bin/env bash

# ALIASES

# Listing directories
alias ls='eza -lh --icons --group-directories-first --sort name --sort extension'
alias ll='eza -lha --icons --group-directories-first --sort name --sort extension'
alias la='eza -a --icons --group-directories-first --sort name --sort extension'

# Workflow
alias ..='cd ..'
alias v='$EDITOR'
alias y='yazi'

# System
alias rm='gtrash put'
alias remove='rm'

# Utils
alias lutil='curl -fsSL christitus.com/linux | sh'
alias rsh='source ~/.bashrc'
