#!/usr/bin/env bash

# ENVS

# Bat theme
export BAT_THEME="base16"

# Editor
export EDITOR="nvim"
export SUDO_EDITOR="$EDITOR"

# Color man pages with bat
export MANROFFOPT="-c"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# History size
export HISTSIZE=32768
export HISTFILESIZE=32768

# Virsh
export LIBVIRT_DEFAULT_URI=qemu:///system
