#!/usr/bin/env bash

# INIT

# Init zoxide
if command -v zoxide >/dev/null 2>&1; then
    eval "$(zoxide init bash)"
fi

# Init starship prompt
if command -v starship >/dev/null 2>&1; then
    eval "$(starship init bash)"
fi

# Init fzf keybindings and completion
if [[ -f "$HOME/.fzf.bash" ]]; then
    source "$HOME/.fzf.bash"
elif command -v fzf-share >/dev/null 2>&1; then
    source "$(fzf-share)/key-bindings.bash"
    source "$(fzf-share)/completion.bash"
fi


# Init homebrew
if command -v brew >/dev/null 2>&1; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv bash)"
fi

