#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

source ~/.config/bash/envs
source ~/.config/bash/aliases
source ~/.config/bash/functions
source ~/.config/bash/init

[[ $- == *i* ]] && bind -f ~/.config/bash/input
