#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Source modular config
source ~/.config/bash/envs
source ~/.config/bash/aliases
source ~/.config/bash/functions
source ~/.config/bash/init

# Source input binds
[[ $- == *i* ]] && bind -f ~/.config/bash/input

