add_newline = true
command_timeout = 200
format = "($custom.ssh_host)[$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
# Define a standard format for when you are NOT in a repo root
format = "[$path]($style)[$read_only]($read_only_style) "
# Keep your existing settings
truncation_length = 2
truncation_symbol = "…/"

[git_branch]
symbol = ""
format = "[$symbol $branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

# Only shown during SSH sessions
[custom.ssh_host]
description = "Display hostname when connected over SSH"
command = "hostname -s"
when = "test -n \"$SSH_CONNECTION\""
format = "[$symbol$output]($style) "
symbol = "󰣀 "
style = "bold blue"
shell = ["sh"]
